### ISSUE TITLE
Return data from run()

### ISSUE THREAD

**Issue by dr-dimitru** [kiliwalk/nbs#1]
It is possible somehow return data from `run` method? Please, see code below:

```js
var nbs = require('nbs'), wait = nbs.wait, resume = nbs.resume;

function sleep(ms){
  setTimeout(function(){
    wait.return "data";
  }, sec);
  wait();
}

data = nbs.run(function(){
  return sleep(10);
});

console.log(data); // Outputs: 'data'
```

**Comment by kiliwalk** [comment]
you can't get the return from the `run` method directly, for `run` is run in async mode. see the code below:
```js
nbs.run(function(){
  console.log('start sleep');
  setTimeout(resume, 1000);
  wait();
  console.log('end sleep');
});
console.log('main');
```
the output will be 
```
start sleep
main
end sleep
```

so, the code in run can be sync, but out of run is async. 
AND this is OK. in most cases, you put the `nbs.run` in the top of the call chain, then the subsequent stack can be used with `resume`/`wait` to achieve the sync behavior.

**Comment by dr-dimitru** [comment]
Thank you for reply, but I'm stuck (and when I'm saying "stuck" it means - I've spend more than week trying to make it work with different libs like `streamline`, `Q` and etc.) with rewriting [this lib](https://github.com/VeliovGroup/ostrio-neo4jdriver/tree/dev) from Meteor dependent lib to Node lib.
As I know Meteor wraps every request into fiber on http-server level (like in yours example), but once I try to run code in plain Node env, it throws "Can't wait without a fiber".

So, I have simple `Future` based helper:
```coffeescript
__wait = (cb) -> 
  fut = new Future()
  cb fut
  return fut.wait()
```

Which used like:
```coffeescript
__wait (fut) ->
   needle.request method, url, body, options, (error, response)->
      if error
         fut.throw error
      else
         fut.return response
```
As lib heavily depend from third party API, it needs to wait until each response is received, and block further execution (in current fiber). Any idea how to solve it?

**Comment by kiliwalk** [comment]
sorry for my poor coffee script ability, and i have never used the fibers `Future` lib. i will try to help. as you mentioned the error "Can't wait without a fiber" above, you should put these code  in the fiber context, which means you should call `futrue()` method as the wrapper of your code, just like `nbs.run()`.
contrast `Future` with `nbs`: 
`future()` -> `run()`
`return()` -> `resume()`
`wait()` -> `wait()`
hope there is any help to you:)

**Comment by kiliwalk** [comment]
i just write a test code to reappear your problem and try the solution. see code below:
```js
/*eslint-disable strict, no-console, no-constant-condition*/
var Future = require('fibers/future');

var __wait = function(cb){
  var fut = new Future();
  cb(fut);
  return fut.wait();
};

function request(cb){
  setTimeout(function(){//just to simulate the async behavior
    cb(null, 'hello world');
  });
}

//this block will throw "Can't wait without a fiber"
__wait(function(fut){
   request(function(error, response){
     if(error) fut.throw(error);
     else fut.return(response);
  });
});

//but this is ok! (comment the block above)
(function(){
  var resp = __wait(function(fut){
     request(function(error, response){
       if(error) fut.throw(error);
       else fut.return(response);
    });
  });
  console.log('response', resp);//response hello world
}).future()();
```

**Comment by dr-dimitru** [comment]
@kiliwalk thank you - very much. After your answer I understood what developers using my lib have to use Fibers along to it.
